[package]
name = "huub"
description = "CP+SAT solver framework built to be reliable, performant, and extensible"

authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
bon = { workspace = true }
dyn-clone = { workspace = true }
flatzinc-serde = { workspace = true, optional	= true }
itertools = { workspace = true }
pindakaas = { workspace = true, features = ["external-propagation"] }
rangelist = { workspace = true }
rustc-hash = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
clap = { workspace = true }
ctrlc = { workspace = true }
expect-test = { workspace = true }
humantime = { workspace = true }
tracing-test = { workspace = true }

[lints]
workspace = true

[features]
flatzinc = ["flatzinc-serde"]
