name: Run Tests

on:
  push:
    branches:
      - "develop"
  pull_request:
  workflow_dispatch:

env:
  RUST_CHANNEL: "stable"
  RUST_TEST_CHANNEL: "nightly"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          cache: false
          channel: ${{ env.RUST_TEST_CHANNEL }}
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Collect coverage data
        run: |
          cargo llvm-cov --no-report nextest --all-features --workspace --tests --bins --examples
          cargo llvm-cov --no-report --doc
          cargo llvm-cov report --doctests --codecov --output-path codecov.json
      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: codecov.json
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ env.RUST_CHANNEL }}
          cache-target: bench
          bins: cargo-codspeed
      - name: Build the benchmark target(s)
        run: cargo codspeed build --profile bench
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: "simulation"
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain and clippy
        uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ env.RUST_CHANNEL }}
          components: clippy
      - name: Run clippy (no extra features)
        run: cargo clippy -p huub --all-targets -- -D warnings
      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ env.RUST_CHANNEL }}
      - name: Run rustdoc
        run: RUSTDOCFLAGS="-D warnings" cargo doc -p huub --no-deps --all-features
